#!/usr/bin/env sh
# <!-- Configuration -->
# vi: ft=sh
set -eu

# <!-- Run the command to reset xrandr configurations to the correct ones -->
xrandr --output "$(xrandr | grep -oP "^([\w\-]+)(?=\sconnected\sprimary)")" \
    --set "scaling mode" "Full" \
    --mode "$(xrandr | grep -oP "(?<=^\s{3})(\d+x\d+)" | head -n1)"
