#!/bin/bash

# This should be your mouse, you can see yours with the command
# $ xinput --list --name-only
MOUSE1="Logitech G403 Prodigy Gaming Mouse"
MOUSE2="Dell Computer Corp Dell Universal Receiver Mouse"

# Attribute, this can be seen with the command, and is usually the default one.
# xinput --list-props "MOUSE"
ATTR="libinput Accel Speed"

# Sensitivity
SENS1=-0.7
SENS2=-1
xinput --set-prop "$MOUSE1" "$ATTR" $SENS1
xinput --set-prop "$MOUSE2" "$ATTR" $SENS2

